version: "2"

services:
  mongo:
    image: mongo

  hapidashboard:
    build: .
    command: npm run start
    ports:
      - "3000:3000"
    depends_on:
      - mongo  
    links:
      - mongo
    environment:
      PORT: 3000
      MONGO: mongo