version: "2"

services:
  mongo:
    image: mongo

  hapidashboard:
    build: .
    image: hapidashboard
    command: bash -c "npm run seed && npm start"
    ports:
      - "3000:3000"
    depends_on:
      - mongo  
    links:
      - mongo
    environment:
      PORT: 3000
      MONGO: mongo
